name: healthflo
description: "HealthFlo - A modular Flutter + Firebase healthcare super app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  flutter_markdown: ^0.6.23

  # Firebase + Related
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  cloud_functions: ^6.0.0

  google_fonts: ^6.2.1
  intl: ^0.20.2
  file_picker: ^8.1.2
  uuid: ^4.4.0
  collection: ^1.18.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
    - assets/lottie/